Executable              = /sharesoft/osg/app/cmssoft/cms/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_9/bin/slc5_amd64_gcc462/cmsRun

Universe                = vanilla
Getenv                  = True
Arguments               = FiveHitsRecoWtoLNu_L1Reco_RECO_PU.py $(Process) 

Output                  = /data/users/jbrinson/FiveHits_2/log/condor_$(Process).out
Error                   = /data/users/jbrinson/FiveHits_2/log/condor_$(Process).err
Log                     = /data/users/jbrinson/FiveHits_2/log/condor_$(Process).log

+IsLocalJob             = true
Rank                    = TARGET.IsLocalSlot

Queue 2001