Executable              = /sharesoft/osg/app/cmssoft/cms/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_9/bin/slc5_amd64_gcc462/cmsRun
x509userproxy		= /tmp/x509up_u522

Universe                = vanilla

Getenv                  = True
Arguments               = /home/jbrinson/DisTrack/mainAN/AnTemp/removeHits/CMSSW_5_3_9/src/FiveHitsRecoWtoLNu_L1Reco_RECO_PU_Test.py $(Process) 


Should_Transfer_Files   = YES
When_To_Transfer_Output = ON_EXIT
#Transfer_Input_Files    = config_cfg.py,userConfig_cfg.py,runList.py

Output                  = /data/users/jbrinson/FiveHits_3/log/condor_$(Process).out
Error                   = /data/users/jbrinson/FiveHits_3/log/condor_$(Process).err
Log                     = /data/users/jbrinson/FiveHits_3/log/condor_$(Process).log

+IsLocalJob             = true
Rank                    = TARGET.IsLocalSlot

Queue 2000