Executable              = /sharesoft/osg/app/cmssoft/cms/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_9/bin/slc5_amd64_gcc462/cmsRun

Universe                = vanilla
Getenv                  = True
Arguments               = TrackRecoSystAnalyzerCondor_cfg.py $(Process) 

Output                  = analyzerOutputAllHits/condor_$(Process).out
Error                   = analyzerOutputAllHits/condor_$(Process).err
Log                     = analyzerOutputAllHits/condor_$(Process).log
+IsLocalJob             = true
Rank                    = TARGET.IsLocalSlot

Queue 2001